name: Deploy to VPS
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: somewhatjustin
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/somewhatjustin/stonefruit:latest

      # Decode Base64-encoded SSH private key
      - name: Decode SSH key
        run: |
          echo "${{ secrets.VPS_SSH_KEY_BASE64 }}" | base64 -d > /tmp/vps_key
          chmod 600 /tmp/vps_key

      # SSH into VPS and restart the stack
      - uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key_path: /tmp/vps_key
          script: |
            cd /opt/stonefruit
            docker compose pull app
            docker compose up -d
            docker image prune -f
